
name: Coockiecutter Testing

on: 
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install Cookiecutter
      run: |
        python -m pip install --upgrade pip
        pip install -q cookiecutter
    - name: Generate Java project
      run: |
        cookiecutter gh:romellfudi/AndroidLibProject -c java  --no-input --overwrite-if-exists
    - name: Testing Java project
      run: cd MyApplication;./gradlew build;cd ..; rm -rf MyApplication;
      
    - name: Generate Kotlin project
      run: |
        cookiecutter gh:romellfudi/AndroidLibProject -c kotlin  --no-input --overwrite-if-exists
    - name: Testing Kotlin project
      run: cd MyApplication;./gradlew build;cd ..; rm -rf MyApplication;
      
    - name: Generate Kotlin DSL project
      run: |
        cookiecutter gh:romellfudi/AndroidLibProject -c kotlin_dsl  --no-input --overwrite-if-exists
    - name: Testing Kotlin DSL project
      run: cd MyApplication;./gradlew build;cd ..; rm -rf MyApplication;